set1:
  # criteria: ['1', '2', '3', '4']
  # costs: ['1', '2']
  alternatives:
    a11_:
      criteria: [9, 3, 3, 6, 4]
      costs: [3, 5]
    a12_:
      criteria: [4, 6, 7, 3, 2]
      costs: [4, 2]
set2:
  # criteria: ['1', '2', '3', '4']
  # costs: ['1', '2']
  alternatives:
    a21_:
      criteria: [1, 3, 7]
      costs: [2, 3]
    a22_:
      criteria: [4, 2, 1]
      costs: [1, 2]
set3:
  # criteria: ['1', '2', '3', '4']
  # costs: ['1', '2']
  alternatives:
    a31_:
      criteria: [1, 3, 7, 4]
      costs: [2, 3, 6]
    a32_:
      criteria: [4, 2, 1, 4]
      costs: [1, 2, 2]
#    a33_:
#       criteria: [2, 2, 1, 2]
#       costs: [1, 5, 2]
